"""Campaign analysis: tables, statistics, figures and LaTeX numbers, computed from results/ only.

Usage:
    python -m qd_damage.analysis.report          # final campaign: results/analysis, media/final, report/generated
    python -m qd_damage.analysis.report --dev    # development runs (*_demo): results/analysis_dev, media/dev

Reads results/repertoires/<run>/{run.json,metrics.csv}, results/oracle/<run>/summary.csv,
results/adaptation/<run>/{summary.csv,trials.csv}, results/rl/*/{curve.csv,rl.json} and results/bonus/.

Statistics. The five repetitions of an adaptation only differ by episode noise, so they are averaged first:
the statistical unit is a (repertoire, damage) pair, i.e. 3 seeds x 12 damages = 36 units per algorithm.
Algorithms are compared with Mann-Whitney tests on these units; ITE and top-k (or grid and continuous ITE)
are compared with paired Wilcoxon signed-rank tests. Units of the same seed share a repertoire, so they are
not fully independent and p-values are indicative.
"""

import argparse

import pandas as pd

from qd_damage.analysis.checks import run_checks
from qd_damage.analysis.data import ALGOS, RES, UNIT, load, load_bonus, units
from qd_damage.analysis.figures import figures
from qd_damage.analysis.latex import write_latex
from qd_damage.analysis.stats import iqr, ite_vs_topk, mann_whitney_table, rl_episodes_to_match
from qd_damage.config import load_run_config, performance_reference
from qd_damage.repertoires import REPO_ROOT


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--dev",
        action="store_true",
        help="analyse the development runs (*_demo) instead: no RL, no bonus, no LaTeX output",
    )
    args = parser.parse_args()
    if args.dev:
        runs_glob, out, fig_dir, tex_dir = "*_demo", RES / "analysis_dev", REPO_ROOT / "media" / "dev" / "figures", None
    else:
        runs_glob, out, fig_dir = "*_seed[0-9]", RES / "analysis", REPO_ROOT / "media" / "final" / "figures"
        tex_dir = REPO_ROOT / "report" / "generated"

    meta, quality, curves, oracle, adapt, trials, rl = load(runs_glob)
    if args.dev:
        rl = pd.DataFrame()
    any_run = next(iter(meta.values()))
    f0, scale = performance_reference(
        load_run_config(any_run["algo"], any_run["profile"])["common"]["env"]["episode_length"]
    )
    # Absolute performance, comparable across repertoires: v = (F - F0) / scale (1 is about 15 m in 12.5 s).
    adapt = adapt.assign(perf_abs=(adapt.recommended_true - f0) / scale)
    trials = trials.assign(perf_abs=(trials.recommended_true - f0) / scale)
    oracle = oracle.assign(oracle_abs=(oracle.oracle_fitness - f0) / scale)
    damaged = oracle[oracle.scenario != "intact"]
    ite = adapt[adapt.method == "ite"]

    tables = {
        "repertoire_quality": quality.groupby("algo")[["qd_score", "coverage", "max_fitness"]].agg(
            ["median", "min", "max"]
        ),
        "resilience_by_damage": damaged.pivot_table(
            index="scenario", columns="algo", values="resilience", aggfunc="median"
        )[ALGOS],
        "stats_resilience": mann_whitney_table(damaged.set_index(UNIT).resilience),
        "oracle_abs_by_damage": damaged.pivot_table(
            index="scenario", columns="algo", values="oracle_abs", aggfunc="median"
        )[ALGOS],
        "adaptation_by_method": adapt.groupby("method")[
            ["trials_used", "pct_oracle", "pct_intact", "perf_abs"]
        ].median(),
        "pct_intact_at_equal_trials": trials[trials.trial.isin([1, 3, 5, 10, 20])].pivot_table(
            index="method", columns="trial", values="pct_intact", aggfunc="median"
        ),
        "ite_by_algo": ite.groupby("algo")[["trials_used", "pct_oracle", "pct_intact", "perf_abs"]].median(),
        "stats_ite_perf_abs": mann_whitney_table(units(ite, "perf_abs")),
        "stats_ite_pct_intact": mann_whitney_table(units(ite, "pct_intact")),
        "ite_vs_topk": ite_vs_topk(trials),
    }
    if not rl.empty:
        tables["rl_episodes_to_match_ite"] = rl_episodes_to_match(rl, adapt)
    out.mkdir(parents=True, exist_ok=True)
    for name, t in tables.items():
        t.to_csv(out / f"{name}.csv")
    bonus = None if args.dev else load_bonus(f0, scale)

    lines = ["# Analysis summary (generated by qd_damage.analysis.report)", "", f"Runs: {', '.join(sorted(meta))}", ""]
    for name, t in tables.items():
        lines += [f"## {name}", "", t.round(3).to_markdown(), ""]
    lines += [
        "## Key numbers",
        "",
        f"- ITE: {iqr(ite.trials_used)} trials (median [Q1 ; Q3]), {iqr(ite.pct_intact)} % of the best intact "
        f"gait, {iqr(ite.pct_oracle)} % of the oracle.",
        f"- Best-intact (no adaptation): {iqr(adapt[adapt.method == 'best_intact'].pct_intact)} % of the best "
        "intact gait.",
        "",
    ]
    (out / "summary.md").write_text("\n".join(lines))

    extra_tables, extra_macros = ({}, {}) if args.dev else run_checks(oracle, adapt, trials, rl, f0, scale, tex_dir)
    for name, t in extra_tables.items():
        t.to_csv(out / f"{name}.csv")
    if tex_dir:
        write_latex(tex_dir, meta, quality, oracle, adapt, trials, tables, bonus, extra_macros)
    for lang, d in (("fr", fig_dir), ("en", fig_dir.with_name("figures_en"))):
        figures(curves, oracle, trials, rl, adapt, bonus, d, f0, scale, lang)
    print((out / "summary.md").read_text())


if __name__ == "__main__":
    main()
